name: tokner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # For data class
  equatable: ^2.0.5

  responsive_builder: ^0.7.0

  # Resource localizations
  flutter_localizations:
    sdk: flutter

  # Support for design
  flutter_svg: 2.0.3

  # Image Cached
  cached_network_image: ^3.2.3

  # Router
  auto_route: ^5.0.4

  intl: ^0.18.0

  # dependency injection
  get_it: ^7.6.0
  injectable: ^2.1.1
  rxdart: ^0.27.2

  # state management
  flutter_bloc: 8.0.1

  # database
  hive: ^2.2.0
  hive_flutter: ^1.1.0

  # For Design Pattern
  flutter_hooks: ^0.18.1
  hooked_bloc: ^1.4.1

  # Json serializable & model
  json_annotation: ^4.8.0
  freezed: ^2.1.1
  freezed_annotation: ^2.0.3
  enum_to_string: ^2.0.1
  connectivity_plus: ^5.0.1

  data:
    path: ./module/data

  domain:
    path: ./module/domain

  remote:
    path: ./module/remote

  shared:
    path: ./module/shared


dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.1.5

  # Auto generate some files
  build_runner: ^2.3.3

  flutter_gen_runner: ^5.2.0
  json_serializable: ^6.7.0

  bloc_test: 9.0.3

  flutter_lints: ^2.0.0

  # auto route
  auto_route_generator: ^5.0.3
# Config generate when build
flutter_gen:
  output: lib/gen/
  line_length: 160
  null_safety: true

  integrations:
    flutter_svg: true
    flare_flutter: true
    lottie: true
  assets:
    enabled: true

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: HankenGrotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/HankenGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/HankenGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/HankenGrotesk-Regular.ttf
          weight: 400

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/HankenGrotesk-Regular.ttf
          weight: 400

    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope.bold.otf
          weight: 700
        - asset: assets/fonts/manrope.semibold.otf
          weight: 600
        - asset: assets/fonts/manrope.medium.otf
          weight: 500
        - asset: assets/fonts/manrope.regular.otf
          weight: 400





flutter_intl:
  enabled: true
  class_name: LanguageTranslation
  main_locale: en
